### ISSUE TITLE
Write down idea clusters from kickoff meeting

### ISSUE THREAD

**Issue by gpestana** [distributed-systems-group/events#1]
We got a picture with the post-it ideas from the kickoff meeting in the meetup log. It would be cool to put that info into text in the meetup notes for it to be easier to read.

**Comment by f-f** [comment]
For context, this pic:

![](https://raw.githubusercontent.com/distributed-systems-group/events-log/master/photos/kickoff_02032017/photo5823339363017272085.jpg)

@gpestana should we open an issue for every talk idea, or should we open "cluster" issues, for discussing how to best start talking about the cluster topic? I'm for the first alternative, and using labels here on github to categorize the talks.

**Comment by gpestana** [comment]
@f-f yeah, I think an issue per idea would be nice and then tag them properly. This way it's easier to clearly see which ideas are more active and which will more easily turn into a talk/whatever soon.

**Comment by gpestana** [comment]
@f-f just added the 'idea clustering' (https://github.com/distributed-systems-group/events/commit/eb6ad90aa5b04d9590c7635365d4ddd1029528f4) to the meetup notes. I will close this issue and open an issue for a talk/event that I propose myself to organise about CRDTs :)

**Comment by f-f** [comment]
Great 👏 I will open issues for some of the ideas I proposed.
